site_name: De-risking custom technology projects
site_url: https://how-to.usopendata.org/
site_description: A playbook for state grantee budgeting and oversight

repo_url: https://github.com/waldoj/technology-budgeting/
docs_dir: .

pages:
- Introduction: index.md
- Basic principles of modern software design:
  - Introduction: basics/index.md
  - User-centered design: basics/ucd.md
  - Agile software development: basics/agile.md
  - Product ownership: basics/product.md
  - DevOps: basics/devops.md
  - Building with loosely coupled parts: basics/loosely-coupled.md
  - Modular contracting: basics/modular-contracting.md
- Plays for budgeting and overseeing tech projects:
  - Think about risk in a new way: plays/risk.md
  - Procure services, not software: plays/services.md
  - Beware the customized commercial software trap: plays/cots.md
  - Require demos, not memos: plays/demos.md
  - Hire tech talent in-house: plays/hire.md
  - Minimize the cost of change: plays/cost-of-change.md
  - Measure success based on iterative outcomes, not project milestones: plays/outcomes.md
  - Limit total spending: plays/limit-spending.md
  - Limit contract sizes: plays/limit-contracts.md
  - Fund systems, not monoliths: plays/systems.md
  - Expand your vendor pool: plays/vendor-pool.md
  - Share your software: plays/share-software.md
  - Budget for software as an operational expense: plays/operational-budget.md
  - Ask technical questions of agencies: plays/ask-questions.md
- "Appendix A: Questions to ask": appendix-a.md
- "Appendix B: Sample Quality Assessment Surveillance Plan": appendix-b.md

theme: readthedocs
